### ISSUE TITLE
npm install not working on raspian

### ISSUE THREAD

**Issue by ShadeJackrabbit** [landau/twit-cli#5]
Run `npm install -g twit-cli`. Result:

```
npm http GET https://registry.npmjs.org/twit-cli

npm ERR! Error: failed to fetch from registry: twit-cli
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "twit-cli"
npm ERR! cwd /home/pi
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: twit-cli
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm not ok
```
Contents of npm-debug.log

```
info it worked if it ends with ok
verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '-g', 'twit-cli' ]
info using npm@1.1.4
info using node@v0.6.19
verbose config file /root/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
silly exec /usr/bin/nodejs "/usr/share/npm/bin/npm-get-uid-gid.js" "nobody" 1000
silly spawning [ '/usr/bin/nodejs',
silly spawning   [ '/usr/share/npm/bin/npm-get-uid-gid.js', 'nobody', 1000 ],
silly spawning   null ]
silly output from getuid/gid {"uid":65534,"gid":1000}
silly output from getuid/gid
verbose cache add [ 'twit-cli', null ]
silly cache add: name, spec, args [ undefined, 'twit-cli', [ 'twit-cli', null ] ]
verbose parsed url { pathname: 'twit-cli', path: 'twit-cli', href: 'twit-cli' }
verbose addNamed [ 'twit-cli', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'twit-cli', '', false ]
verbose raw, before any munging twit-cli
verbose url resolving [ 'https://registry.npmjs.org/', './twit-cli' ]
verbose url resolved https://registry.npmjs.org/twit-cli
http GET https://registry.npmjs.org/twit-cli
ERR! Error: failed to fetch from registry: twit-cli
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.g (events.js:156:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /home/pi/npm-debug.log npm
ERR!
ERR! System Linux 3.12.28+
ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "twit-cli"
ERR! cwd /home/pi
ERR! node -v v0.6.19
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: twit-cli
verbose exit [ 1, true ]
```

**Comment by landau** [comment]
I haven't touched this in sometime. If you want to to fix the problem I'll gladly merge and update the project.
